### ISSUE TITLE
There are not outputs in my IE browser

### ISSUE THREAD

**Issue by oaright** [yyjhao/sublime-text-markmon#10]
I run the markmon commond from the sublime text, no errors spit out, and the following messages show up from the CMD windows: 
`(node) sys is deprecated. Use util instead.
express deprecated app.configure: Check app.get('env') in an if statement C:\Pro
gram Files\nodejs\node_modules\markmon\lib\Server.js:32:9
connect deprecated multipart: use parser (multiparty, busboy, formidable) npm mo
dule instead C:\Program Files\nodejs\node_modules\markmon\node_modules\express\n
ode_modules\connect\lib\middleware\bodyParser.js:56:20
connect deprecated limit: Restrict request size at location of read C:\Program F
iles\nodejs\node_modules\markmon\node_modules\express\node_modules\connect\lib\m
iddleware\multipart.js:86:15
   info  - socket.io started
express deprecated app.del: Use app.delete instead C:\Program Files\nodejs\node_
modules\markmon\lib\Server.js:70:9
Listening on 3002
   info  - handshake authorized lfNNbkfFGA9-e5_v0D-o`

IE browser pop up, unfortunately there are output in it with only the title change to "Markmon", Is there any suggestion for me ?

**Comment by yyjhao** [comment]
what's the version of your IE?

**Comment by oaright** [comment]
My IE version is 11, and I have tried Chrome and get the same result. 
I reinstall the node.js, windows 7 SDK and markmon module. Meanwhile I reinstall another version of sublimetext and the markmon plugin. Now I get the following errors poping up from the sublime text and the CMD window show up for a second and is terminted:
`Exception in thread Thread-3:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "./threading.py", line 1142, in run
  File "D:\SublimeText3\Data\Packages\sublime-text-markmon-master\markmon.py", line 43, in display
    self.client.view_updated(current_view)
  File "D:\SublimeText3\Data\Packages\sublime-text-markmon-master\markmon.py", line 102, in view_updated
    connection.getresponse()
  File "./http/client.py", line 1147, in getresponse
  File "./http/client.py", line 358, in begin
  File "./http/client.py", line 320, in _read_status
  File "./socket.py", line 297, in readinto
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接`

I have closed the firewall. So what is wrong? Is there any suggestion for me??

**Comment by oaright** [comment]
`Traceback (most recent call last):
  File "D:\SublimeText3\sublime_plugin.py", line 533, in run_
    return self.run(**args)
  File "D:\SublimeText3\Data\Packages\sublime-text-markmon-master\commands.py", line 21, in run
    markmon.markmon.set_running(True)
  File "D:\SublimeText3\Data\Packages\sublime-text-markmon-master\markmon.py", line 56, in set_running
    self.display()
  File "D:\SublimeText3\Data\Packages\sublime-text-markmon-master\markmon.py", line 43, in display
    self.client.view_updated(current_view)
  File "D:\SublimeText3\Data\Packages\sublime-text-markmon-master\markmon.py", line 102, in view_updated
    connection.getresponse()
  File "./http/client.py", line 1147, in getresponse
  File "./http/client.py", line 358, in begin
  File "./http/client.py", line 320, in _read_status
  File "./socket.py", line 297, in readinto
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
Markmon server is down. Check your preferences.`

**Comment by yyjhao** [comment]
Are you sure you have disabled your firewall? Are there some default firewall working or something? ConnectionReset seems to be caused by firewall.

**Comment by oaright** [comment]
I am sure I have disabled the firewall of  Windows 7, and I have uninstalled  the symantec endpoint protection 12 on my computer. I googled and get nothing. /(ㄒoㄒ)/~~

**Comment by yyjhao** [comment]
Did you try testing with simple documents? Wondering if it's due to special characters or length of document.
