### ISSUE TITLE
nothing happened after setting 'Makmon launch' in sublime 3

### ISSUE THREAD

**Issue by kreja** [yyjhao/sublime-text-markmon#14]
It worked fine when I was using sublime 2, and I really like this plugin! 
However, nothing happened after I set Makmon launch in sublime 3.
But it works fine when I use CLI.

**Comment by GregHilston** [comment]
I'm running into this issue as well. I'm using Sublime 3, stable build, version 3114.

**Comment by Darkside73** [comment]
I've opened a Sublime Text console and seen the following:

```
Markmon Server failed to initialize. Confirm executable path is correct in Markmon Setting. Command used:
['markmon', '--port', '3002', '--command', 'pandoc -t HTML5 --mathjax']
Traceback (most recent call last):
  File "markmon in /home/darkside/.config/sublime-text-3/Installed Packages/Markmon real-time markdown preview.sublime-package", line 101, in view_updated
  File "./python3.3/http/client.py", line 1065, in request
  File "./python3.3/http/client.py", line 1103, in _send_request
  File "./python3.3/http/client.py", line 1061, in endheaders
  File "./python3.3/http/client.py", line 906, in _send_output
  File "./python3.3/http/client.py", line 844, in send
  File "./python3.3/http/client.py", line 822, in connect
  File "./python3.3/socket.py", line 435, in create_connection
  File "./python3.3/socket.py", line 426, in create_connection
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 333, in on_activated_async
    callback.on_activated_async(v)
  File "MarkmonListener in /home/darkside/.config/sublime-text-3/Installed Packages/Markmon real-time markdown preview.sublime-package", line 42, in on_activated_async
  File "markmon in /home/darkside/.config/sublime-text-3/Installed Packages/Markmon real-time markdown preview.sublime-package", line 106, in view_updated
  File "markmon in /home/darkside/.config/sublime-text-3/Installed Packages/Markmon real-time markdown preview.sublime-package", line 130, in setup_server
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1448, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'markmon'
```

**Comment by kreja** [comment]
@Darkside73  I opened the console and found that I was meeting the same problem as you.

So I used `which markmon` to get the path of markmon on my computer. Then went to Sublime Text → Preferences → Package Settings → Markmon → Settings(User) , and update the 'executable' parameter :  `"executable": "path/to/markmon"`. And it works pretty fine now! 😆
