### ISSUE TITLE
Crashes at runtime: "ConnectionRefusedError: [Errno 61] Connection refused"

### ISSUE THREAD

**Issue by ryanmcginnis** [yyjhao/sublime-text-markmon#15]
Env:
macOS 10.12.4
Sublime Text Stable Channel, Build 3126

Steps to reproduce:
1. Install package as describe in README.md
2. Attempt to launch in Sublime Text.
3. Observe the following error:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 530, in on_activated_async
    callback.on_activated_async(v)
  File "MarkmonListener in /Users/rrm/Library/Application Support/Sublime Text 3/Installed Packages/Markmon real-time markdown preview.sublime-package", line 42, in on_activated_async
  File "markmon in /Users/rrm/Library/Application Support/Sublime Text 3/Installed Packages/Markmon real-time markdown preview.sublime-package", line 108, in view_updated
  File "markmon in /Users/rrm/Library/Application Support/Sublime Text 3/Installed Packages/Markmon real-time markdown preview.sublime-package", line 102, in view_updated
  File "./python3.3/http/client.py", line 1147, in getresponse
  File "./python3.3/http/client.py", line 358, in begin
  File "./python3.3/http/client.py", line 328, in _read_status
http.client.BadStatusLine: ''
Traceback (most recent call last):
  File "markmon in /Users/rrm/Library/Application Support/Sublime Text 3/Installed Packages/Markmon real-time markdown preview.sublime-package", line 101, in view_updated
  File "./python3.3/http/client.py", line 1065, in request
  File "./python3.3/http/client.py", line 1103, in _send_request
  File "./python3.3/http/client.py", line 1061, in endheaders
  File "./python3.3/http/client.py", line 906, in _send_output
  File "./python3.3/http/client.py", line 844, in send
  File "./python3.3/http/client.py", line 822, in connect
  File "./python3.3/socket.py", line 435, in create_connection
  File "./python3.3/socket.py", line 426, in create_connection
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 795, in run_
    return self.run(**args)
  File "commands in /Users/rrm/Library/Application Support/Sublime Text 3/Installed Packages/Markmon real-time markdown preview.sublime-package", line 21, in run
  File "markmon in /Users/rrm/Library/Application Support/Sublime Text 3/Installed Packages/Markmon real-time markdown preview.sublime-package", line 56, in set_running
  File "markmon in /Users/rrm/Library/Application Support/Sublime Text 3/Installed Packages/Markmon real-time markdown preview.sublime-package", line 43, in display
  File "markmon in /Users/rrm/Library/Application Support/Sublime Text 3/Installed Packages/Markmon real-time markdown preview.sublime-package", line 108, in view_updated
  File "markmon in /Users/rrm/Library/Application Support/Sublime Text 3/Installed Packages/Markmon real-time markdown preview.sublime-package", line 102, in view_updated
  File "./python3.3/http/client.py", line 1147, in getresponse
  File "./python3.3/http/client.py", line 358, in begin
  File "./python3.3/http/client.py", line 328, in _read_status
http.client.BadStatusLine: ''
```

**Comment by xiaoxiyouran** [comment]
I get the same error
