### ISSUE TITLE
ConnectionRefusedError and ConnectionResetError raised

### ISSUE THREAD

**Issue by yuntan** [yyjhao/sublime-text-markmon#4]
env: Sublime Text3 build 3065; Arch linux

When I run `markmon launch`, I got this error

```
Traceback (most recent call last):
  File "/home/yuntan/.config/sublime-text-3/Packages/sublime-text-markmon/markmon.py", line 101, in view_updated
    connection.request('PUT', '/', view.substr(sublime.Region(0, view.size())).encode('utf-8'))
  File "./http/client.py", line 1065, in request
  File "./http/client.py", line 1103, in _send_request
  File "./http/client.py", line 1061, in endheaders
  File "./http/client.py", line 906, in _send_output
  File "./http/client.py", line 844, in send
  File "./http/client.py", line 822, in connect
  File "./socket.py", line 435, in create_connection
  File "./socket.py", line 426, in create_connection
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/sublime_text_3/sublime_plugin.py", line 311, in on_activated_async
    callback.on_activated_async(v)
  File "/home/yuntan/.config/sublime-text-3/Packages/sublime-text-markmon/MarkmonListener.py", line 42, in on_activated_async
    callback(view)
  File "/home/yuntan/.config/sublime-text-3/Packages/sublime-text-markmon/markmon.py", line 108, in view_updated
    self.view_updated(view, False)
  File "/home/yuntan/.config/sublime-text-3/Packages/sublime-text-markmon/markmon.py", line 102, in view_updated
    connection.getresponse()
  File "./http/client.py", line 1147, in getresponse
  File "./http/client.py", line 358, in begin
  File "./http/client.py", line 320, in _read_status
  File "./socket.py", line 297, in readinto
ConnectionResetError: [Errno 104] Connection reset by peer
```

My setting: 

```json
{
    "port": 3000,
    "executable": "markmon",
    "command": "pandoc -t HTML5 --mathjax",
    "stylesheet": null,
    "projectdir": null
}
```

I can run `markmon hoge.md --port 3000 --command "pandoc -t HTML5 --mathjax"` from command line and this works fine (I can read markdown file on browser, and when file is modified, contents on browser correctly updated).

**Comment by yyjhao** [comment]
It seems that #5 may fix this issue. I have made a new release, can you test this out and see if it works for you now?

**Comment by yuntan** [comment]
Umm, seems doesn't fix the problem...

I got following error, similar to previous comment

```
Traceback (most recent call last):
Exception in thread Thread-20:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "./threading.py", line 1142, in run
  File "/home/yuntan/.config/sublime-text-3/Packages/sublime-text-markmon/markmon.py", line 43, in display
    self.client.view_updated(current_view)
  File "/home/yuntan/.config/sublime-text-3/Packages/sublime-text-markmon/markmon.py", line 102, in view_updated
    connection.getresponse()
  File "./http/client.py", line 1147, in getresponse
  File "./http/client.py", line 358, in begin
  File "./http/client.py", line 328, in _read_status
http.client.BadStatusLine: ''

  File "/home/yuntan/.config/sublime-text-3/Packages/sublime-text-markmon/markmon.py", line 101, in view_updated
    connection.request('PUT', '/', view.substr(sublime.Region(0, view.size())).encode('utf-8'))
  File "./http/client.py", line 1065, in request
  File "./http/client.py", line 1103, in _send_request
  File "./http/client.py", line 1061, in endheaders
  File "./http/client.py", line 906, in _send_output
  File "./http/client.py", line 844, in send
  File "./http/client.py", line 822, in connect
  File "./socket.py", line 435, in create_connection
  File "./socket.py", line 426, in create_connection
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/sublime_text_3/sublime_plugin.py", line 312, in on_activated_async
    callback.on_activated_async(v)
  File "/home/yuntan/.config/sublime-text-3/Packages/sublime-text-markmon/MarkmonListener.py", line 42, in on_activated_async
    callback(view)
  File "/home/yuntan/.config/sublime-text-3/Packages/sublime-text-markmon/markmon.py", line 108, in view_updated
    self.view_updated(view, False)
  File "/home/yuntan/.config/sublime-text-3/Packages/sublime-text-markmon/markmon.py", line 102, in view_updated
    connection.getresponse()
  File "./http/client.py", line 1147, in getresponse
  File "./http/client.py", line 358, in begin
  File "./http/client.py", line 320, in _read_status
  File "./socket.py", line 297, in readinto
ConnectionResetError: [Errno 104] Connection reset by peer
```

I put pandoc to system path so I don't use `pandoc_path`. 

(env: sublime build 3083, 71e0c62 , markmon 0.0.7, pandoc 1.13.2)

**Comment by yyjhao** [comment]
Can it be that you have a firewall that blocks certain requests? The request to 'push' content to marksman is done via 'PUT' which is different from the GET request to retrieve the webpage.

**Comment by ekevjn** [comment]
i face this problem too, there was no firewall enable in my system. When i took a look into markmon code i found that was connection refused exception.
